### ISSUE TITLE
Add newt altars to minimap

### ISSUE THREAD

**Issue by Gl33m** [DekuDesu/MiniMapMod#24]
It would be great if you could add the newt altars to the minimap. Currently, even with everything turned on, they do not show. I'd be happy to donate 30 dollars to your listed charity for this feature.

**Comment by DekuDesu** [comment]
Thank you for your suggestion, however the lack of the Newt Altar in the minimap is an intentional feature. 

This may change in the future but for now there is no plan for this to be added.

**Comment by Gl33m** [comment]
That is unfortunate. May I ask your reason for specifically excluding newt altars?

**Comment by DekuDesu** [comment]
> May I ask your reason for specifically excluding newt altars?

The intentional exclusion of the lack of newt altars in the minimap is to reward map knowledge and to avoid undermining the original developers intention for having secret intermediary levels.

However, an argument could be made that my minimaps inclusion some other features undermines that exact intention.

Nevertheless I have no plan on implementing this feature, thank you for your suggestion.
